/**
 * Interface copy for site 1.
 *
 * Facts and figures never live here — those come from content.json. This file
 * holds only chrome: navigation, buttons, form labels, validation messages and
 * section framing. Each site has its own copy because each site has its own tone.
 *
 * `en` is the reference shape; `uz` and `ru` are typed against it, so a missing
 * key is a compile error rather than a blank on the page.
 */

const en = {
  meta: {
    title: 'Invest in Uzbekistan — One-Stop-Shop for foreign investors',
    description:
      'Macro indicators, ten priority sectors, agency services, special economic zones and the Uzbekistan-2030 strategy. Concept/demo project — official information: invest.gov.uz',
  },
  skipToContent: 'Skip to content',
  navLabel: 'Main navigation',
  nav: {
    why: 'Why Uzbekistan',
    human: 'Human capital',
    sectors: 'Sectors',
    services: 'Services',
    sez: 'SEZ & incentives',
    strategy: 'Strategy 2030',
    tiif: 'TIIF 2026',
    journey: 'Investor journey',
    faq: 'FAQ',
    contact: 'Contact',
  },
  actions: {
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    enquiry: 'Send an investment enquiry',
    /** Header variant — the full label wraps to two lines in the sticky bar. */
    enquiryShort: 'Send enquiry',
    whyUzbekistan: 'Why Uzbekistan',
    readMore: 'Read more',
    close: 'Close',
    officialPage: 'Official sector page',
    retry: 'Try again',
    copy: 'Copy',
    copied: 'Copied',
    sortByValue: 'Sort by value',
    sortByName: 'Sort by name',
    backToTop: 'Back to top',
  },
  theme: { label: 'Colour theme', light: 'Light', dark: 'Dark' },
  language: { label: 'Language', uz: 'Oʻzbekcha', ru: 'Русский', en: 'English' },

  state: {
    loading: 'Loading data…',
    errorTitle: 'Could not load the data',
    errorBody: 'The figures on this page come from a single data file that did not load.',
    empty: 'Nothing matches that search.',
    noData: 'No data',
  },

  hero: {
    eyebrow: 'Investment Promotion Agency',
    titleLead: 'One address for',
    titleAccent: 'investing in Uzbekistan',
    body: 'Information, site selection, meetings with government and business, sector reports and aftercare — from a single point of contact with the state.',
    kpiNote: 'Key indicators, 2025',
  },
  trust: { prefix: 'TIIF 2026' },

  why: {
    eyebrow: 'Why Uzbekistan',
    title: 'An economy growing at pace',
    body: 'Macroeconomic indicators for 2025, as published by the Agency.',
    structureTitle: 'Structure of GDP',
    structureHint: 'Select a segment to see what sits inside it.',
    backToTotal: 'All sectors',
    driversTitle: 'What is driving growth',
  },
  human: {
    eyebrow: 'Human capital',
    title: 'A young country',
    body: 'Demography and the labour market — the workforce behind every project.',
    salaryTitle: 'Average monthly salary by region',
    salaryUnit: 'thousand UZS / month',
    nationalAverage: 'National average',
    populationNote:
      'Two official pages give two population figures for 2025. Both are shown with their own label rather than averaged.',
  },
  sectors: {
    eyebrow: 'Priority sectors',
    title: 'Ten sectors open to investment',
    body: 'Search or filter, then open the Agency page for the sector you need.',
    searchLabel: 'Search sectors',
    searchPlaceholder: 'Search by name…',
    count: (n: number, total: number) => `${n} of ${total} sectors`,
    modalNote:
      'The Agency does not publish a short summary for each sector. Open the official page for current conditions and projects.',
  },
  services: {
    eyebrow: 'What the Agency does',
    title: 'A One-Stop-Shop',
    body: 'Five services for foreign investors, and the mandate behind them.',
    functionsTitle: 'Statutory functions',
    legalBasis: 'Legal basis',
  },
  sez: {
    eyebrow: 'Special economic zones',
    title: 'Zones and incentives',
    // Deliberately not "incentives depend on the zone, the activity and the
    // size of the investment" — that sentence is already one of the points.
    body: 'What the zones are, what they offer, and where the limits of that offer lie.',
    zoneTypesTitle: 'Types of zone',
    disclaimerTitle: 'This is not tax or legal advice',
  },
  strategy: {
    eyebrow: 'Uzbekistan — 2030',
    title: 'Five priorities, one hundred goals',
    goalsLabel: 'goals',
    adopted: 'Adopted',
    targetsTitle: 'Stated targets',
    progressTitle: 'Since adoption',
  },
  tiif: {
    eyebrow: 'Tashkent International Investment Forum',
    title: 'TIIF 2026 — what the fifth forum delivered',
    pastNotice: 'This forum has taken place. The figures below are its published results.',
    heldOn: 'Held',
    attendeesTitle: 'Organisations represented',
    attendeesNote: 'Names are listed as text only; no third-party logos are used.',
    officialSite: 'Forum website',
  },
  journey: {
    eyebrow: 'How it works',
    title: 'From first enquiry to aftercare',
    stepLabel: (n: number) => `Step ${n}`,
  },
  faq: {
    eyebrow: 'Questions',
    title: 'Frequently asked',
    searchLabel: 'Search questions',
    searchPlaceholder: 'Search the answers…',
  },
  contact: {
    eyebrow: 'Get in touch',
    title: 'Send an investment enquiry',
    body: 'The Agency is the primary point of contact with the state for foreign investors.',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    openMap: 'Open in Maps',
    draftSaved: 'Draft saved',
    draftRestored: 'Your unsent draft was restored.',
    clearDraft: 'Clear the form',
    form: {
      name: 'Full name',
      company: 'Company',
      country: 'Country',
      email: 'Work email',
      sector: 'Sector of interest',
      sectorAny: 'Not decided yet',
      amount: 'Planned investment',
      amountAny: 'Prefer not to say',
      message: 'What would you like to discuss?',
      submit: 'Send enquiry',
      submitting: 'Sending…',
      required: 'Required',
      optional: 'Optional',
    },
    errors: {
      nameRequired: 'Please enter your name.',
      nameShort: 'Please enter at least two characters.',
      emailRequired: 'Please enter an email address.',
      emailInvalid: 'That does not look like an email address.',
      messageRequired: 'Please tell us what you would like to discuss.',
      messageShort: 'A sentence or two is enough.',
      countryRequired: 'Please enter your country.',
    },
    success: {
      title: 'Thank you — your enquiry is ready to send',
      mailto:
        'Your email client should have opened with the message prefilled. If it did not, write to the address above.',
      posted: 'Your enquiry has been submitted.',
    },
    failure: {
      title: 'The enquiry could not be sent',
      body: 'Please write to the address above instead.',
    },
  },
  fx: {
    label: 'Central Bank rate',
    live: 'Live',
    stored: 'Stored rate',
    asOf: (date: string) => `as of ${date}`,
    unavailable: 'Rate unavailable',
  },
  sources: {
    label: 'Source',
    asOf: (date: string) => `Figure as of ${date}`,
    sectionTitle: 'Sources',
    sectionBody: 'Every figure on this page comes from one of the following, on the date shown.',
    verifyBadge: 'Re-check before launch',
    machineTranslation: 'Russian on this page was translated from English and is not an official text.',
  },
  footer: {
    usefulLinks: 'Official links',
    disclaimerTitle: 'Concept project',
    disclaimer:
      'This site is a concept/demo project and is not operated by the Agency. For official information see invest.gov.uz.',
    rights: (year: number) => `© ${year} — concept project`,
  },
};

/** `en` is deliberately not `as const`: the other locales must match its shape,
 *  not its literal values. */
export type UiStrings = typeof en;

const uz: UiStrings = {
  meta: {
    title: 'Invest in Uzbekistan — xorijiy investorlar uchun yagona darcha',
    description:
      'Makroiqtisodiy koʻrsatkichlar, 10 ustuvor sektor, agentlik xizmatlari, maxsus iqtisodiy zonalar va “Oʻzbekiston — 2030” strategiyasi. Konsept/demo loyiha — rasmiy maʼlumot: invest.gov.uz',
  },
  skipToContent: 'Asosiy mazmunga oʻtish',
  navLabel: 'Asosiy navigatsiya',
  nav: {
    why: 'Nega Oʻzbekiston',
    human: 'Inson kapitali',
    sectors: 'Sektorlar',
    services: 'Xizmatlar',
    sez: 'SIZ va imtiyozlar',
    strategy: 'Strategiya 2030',
    tiif: 'TIIF 2026',
    journey: 'Investor yoʻli',
    faq: 'Savollar',
    contact: 'Aloqa',
  },
  actions: {
    openMenu: 'Menyuni ochish',
    closeMenu: 'Menyuni yopish',
    enquiry: 'Investitsiya soʻrovi yuborish',
    enquiryShort: 'Soʻrov yuborish',
    whyUzbekistan: 'Nega Oʻzbekiston',
    readMore: 'Batafsil',
    close: 'Yopish',
    officialPage: 'Rasmiy sektor sahifasi',
    retry: 'Qayta urinish',
    copy: 'Nusxa olish',
    copied: 'Nusxa olindi',
    sortByValue: 'Qiymat boʻyicha',
    sortByName: 'Nom boʻyicha',
    backToTop: 'Yuqoriga',
  },
  theme: { label: 'Rang mavzusi', light: 'Yorugʻ', dark: 'Qorongʻi' },
  language: { label: 'Til', uz: 'Oʻzbekcha', ru: 'Русский', en: 'English' },

  state: {
    loading: 'Maʼlumot yuklanmoqda…',
    errorTitle: 'Maʼlumotni yuklab boʻlmadi',
    errorBody: 'Sahifadagi barcha raqamlar bitta maʼlumot faylidan olinadi — u yuklanmadi.',
    empty: 'Soʻrovga mos natija topilmadi.',
    noData: 'Maʼlumot yoʻq',
  },

  hero: {
    eyebrow: 'Investitsiyalarni jalb qilish agentligi',
    titleLead: 'Oʻzbekistonga investitsiya kiritish uchun',
    titleAccent: 'yagona manzil',
    body: 'Maʼlumot, joy tanlash, davlat va biznes bilan uchrashuvlar, tarmoq hisobotlari va keyingi qoʻllab-quvvatlash — davlat bilan yagona aloqa nuqtasi orqali.',
    kpiNote: 'Asosiy koʻrsatkichlar, 2025',
  },
  trust: { prefix: 'TIIF 2026' },

  why: {
    eyebrow: 'Nega Oʻzbekiston',
    title: 'Tez sur’atda oʻsayotgan iqtisodiyot',
    body: 'Agentlik eʼlon qilgan 2025 yil makroiqtisodiy koʻrsatkichlari.',
    structureTitle: 'YaIM tuzilmasi',
    structureHint: 'Ichki taqsimotni koʻrish uchun boʻlakni tanlang.',
    backToTotal: 'Barcha tarmoqlar',
    driversTitle: 'Oʻsishni nima harakatlantiradi',
  },
  human: {
    eyebrow: 'Inson kapitali',
    title: 'Yosh mamlakat',
    body: 'Demografiya va mehnat bozori — har bir loyiha ortidagi ishchi kuchi.',
    salaryTitle: 'Hududlar boʻyicha oʻrtacha oylik maosh',
    salaryUnit: 'ming soʻm / oyiga',
    nationalAverage: 'Respublika oʻrtachasi',
    populationNote:
      'Ikki rasmiy sahifa 2025 yil uchun ikki xil aholi sonini beradi. Ikkalasi ham oʻz yorligʻi bilan koʻrsatilgan, oʻrtachasi olinmagan.',
  },
  sectors: {
    eyebrow: 'Ustuvor sektorlar',
    title: 'Investitsiya uchun ochiq oʻnta sektor',
    body: 'Qidiring yoki filtrlang, soʻng kerakli sektorning agentlik sahifasini oching.',
    searchLabel: 'Sektorlarni qidirish',
    searchPlaceholder: 'Nomi boʻyicha qidirish…',
    count: (n: number, total: number) => `${total} sektordan ${n} tasi`,
    modalNote:
      'Agentlik har bir sektor uchun qisqa tavsif eʼlon qilmaydi. Joriy shartlar va loyihalar uchun rasmiy sahifani oching.',
  },
  services: {
    eyebrow: 'Agentlik nima qiladi',
    title: 'Yagona darcha',
    body: 'Xorijiy investorlar uchun besh xizmat va ular ortidagi vakolat.',
    functionsTitle: 'Asosiy funksiyalar',
    legalBasis: 'Huquqiy asos',
  },
  sez: {
    eyebrow: 'Maxsus iqtisodiy zonalar',
    title: 'Zonalar va imtiyozlar',
    body: 'Zonalar nima, ular nima beradi va bu taklifning chegarasi qayerda.',
    zoneTypesTitle: 'Zona turlari',
    disclaimerTitle: 'Bu soliq yoki huquqiy maslahat emas',
  },
  strategy: {
    eyebrow: 'Oʻzbekiston — 2030',
    title: 'Besh ustuvor yoʻnalish, yuzta maqsad',
    goalsLabel: 'maqsad',
    adopted: 'Qabul qilingan',
    targetsTitle: 'Eʼlon qilingan maqsadlar',
    progressTitle: 'Qabul qilingandan beri',
  },
  tiif: {
    eyebrow: 'Toshkent xalqaro investitsiya forumi',
    title: 'TIIF 2026 — beshinchi forum natijalari',
    pastNotice: 'Bu forum boʻlib oʻtgan. Quyidagi raqamlar — uning eʼlon qilingan natijalari.',
    heldOn: 'Oʻtkazilgan',
    attendeesTitle: 'Ishtirok etgan tashkilotlar',
    attendeesNote: 'Nomlar faqat matn koʻrinishida; uchinchi tomon logotiplari ishlatilmagan.',
    officialSite: 'Forum sayti',
  },
  journey: {
    eyebrow: 'Qanday ishlaydi',
    title: 'Birinchi murojaatdan loyiha kuzatuviga qadar',
    stepLabel: (n: number) => `${n}-qadam`,
  },
  faq: {
    eyebrow: 'Savollar',
    title: 'Koʻp beriladigan savollar',
    searchLabel: 'Savollarni qidirish',
    searchPlaceholder: 'Javoblardan qidirish…',
  },
  contact: {
    eyebrow: 'Bogʻlanish',
    title: 'Investitsiya soʻrovi yuborish',
    body: 'Agentlik — xorijiy investorlar uchun davlat bilan asosiy aloqa nuqtasi.',
    phone: 'Telefon',
    email: 'Elektron pochta',
    address: 'Manzil',
    openMap: 'Xaritada ochish',
    draftSaved: 'Qoralama saqlandi',
    draftRestored: 'Yuborilmagan qoralamangiz tiklandi.',
    clearDraft: 'Formani tozalash',
    form: {
      name: 'Toʻliq ism',
      company: 'Kompaniya',
      country: 'Mamlakat',
      email: 'Ish elektron pochtasi',
      sector: 'Qiziqish sektori',
      sectorAny: 'Hali tanlanmagan',
      amount: 'Rejalashtirilgan investitsiya',
      amountAny: 'Aytishni istamayman',
      message: 'Nimani muhokama qilmoqchisiz?',
      submit: 'Soʻrovni yuborish',
      submitting: 'Yuborilmoqda…',
      required: 'Majburiy',
      optional: 'Ixtiyoriy',
    },
    errors: {
      nameRequired: 'Ismingizni kiriting.',
      nameShort: 'Kamida ikkita belgi kiriting.',
      emailRequired: 'Elektron pochta manzilini kiriting.',
      emailInvalid: 'Bu elektron pochta manziliga oʻxshamaydi.',
      messageRequired: 'Nimani muhokama qilmoqchi ekaningizni yozing.',
      messageShort: 'Bir-ikki gap yetarli.',
      countryRequired: 'Mamlakatingizni kiriting.',
    },
    success: {
      title: 'Rahmat — soʻrovingiz yuborishga tayyor',
      mailto:
        'Pochta ilovangiz tayyor xat bilan ochilgan boʻlishi kerak. Agar ochilmagan boʻlsa, yuqoridagi manzilga yozing.',
      posted: 'Soʻrovingiz yuborildi.',
    },
    failure: {
      title: 'Soʻrovni yuborib boʻlmadi',
      body: 'Iltimos, yuqoridagi manzilga yozing.',
    },
  },
  fx: {
    label: 'Markaziy bank kursi',
    live: 'Jonli',
    stored: 'Saqlangan kurs',
    asOf: (date: string) => `${date} holatiga`,
    unavailable: 'Kurs mavjud emas',
  },
  sources: {
    label: 'Manba',
    asOf: (date: string) => `Raqam ${date} holatiga`,
    sectionTitle: 'Manbalar',
    sectionBody: 'Sahifadagi har bir raqam quyidagilardan birida koʻrsatilgan sanadagi holat boʻyicha olingan.',
    verifyBadge: 'Eʼlon qilishdan oldin tekshiring',
    machineTranslation: 'Sahifadagi ruscha matn ingliz tilidan tarjima qilingan va rasmiy matn emas.',
  },
  footer: {
    usefulLinks: 'Rasmiy havolalar',
    disclaimerTitle: 'Konsept loyiha',
    disclaimer:
      'Ushbu sayt konsept/demo loyiha boʻlib, agentlik tomonidan yuritilmaydi. Rasmiy maʼlumot uchun: invest.gov.uz.',
    rights: (year: number) => `© ${year} — konsept loyiha`,
  },
};

const ru: UiStrings = {
  meta: {
    title: 'Invest in Uzbekistan — единое окно для иностранных инвесторов',
    description:
      'Макропоказатели, десять приоритетных отраслей, услуги Агентства, специальные экономические зоны и стратегия «Узбекистан — 2030». Концепт/демо — официальная информация: invest.gov.uz',
  },
  skipToContent: 'Перейти к содержимому',
  navLabel: 'Основная навигация',
  nav: {
    why: 'Почему Узбекистан',
    human: 'Человеческий капитал',
    sectors: 'Отрасли',
    services: 'Услуги',
    sez: 'СЭЗ и льготы',
    strategy: 'Стратегия 2030',
    tiif: 'ТМИФ 2026',
    journey: 'Путь инвестора',
    faq: 'Вопросы',
    contact: 'Контакты',
  },
  actions: {
    openMenu: 'Открыть меню',
    closeMenu: 'Закрыть меню',
    enquiry: 'Отправить инвестиционный запрос',
    enquiryShort: 'Отправить запрос',
    whyUzbekistan: 'Почему Узбекистан',
    readMore: 'Подробнее',
    close: 'Закрыть',
    officialPage: 'Официальная страница отрасли',
    retry: 'Попробовать снова',
    copy: 'Копировать',
    copied: 'Скопировано',
    sortByValue: 'По значению',
    sortByName: 'По названию',
    backToTop: 'Наверх',
  },
  theme: { label: 'Цветовая тема', light: 'Светлая', dark: 'Тёмная' },
  language: { label: 'Язык', uz: 'Oʻzbekcha', ru: 'Русский', en: 'English' },

  state: {
    loading: 'Загрузка данных…',
    errorTitle: 'Не удалось загрузить данные',
    errorBody: 'Все цифры на этой странице берутся из одного файла данных — он не загрузился.',
    empty: 'Ничего не найдено.',
    noData: 'Нет данных',
  },

  hero: {
    eyebrow: 'Агентство по привлечению инвестиций',
    titleLead: 'Единый адрес для',
    titleAccent: 'инвестиций в Узбекистан',
    body: 'Информация, подбор площадки, встречи с государством и бизнесом, отраслевые отчёты и последующее сопровождение — через одну точку контакта с государством.',
    kpiNote: 'Ключевые показатели, 2025',
  },
  trust: { prefix: 'ТМИФ 2026' },

  why: {
    eyebrow: 'Почему Узбекистан',
    title: 'Экономика, растущая высокими темпами',
    body: 'Макроэкономические показатели 2025 года по публикации Агентства.',
    structureTitle: 'Структура ВВП',
    structureHint: 'Выберите сегмент, чтобы увидеть его состав.',
    backToTotal: 'Все отрасли',
    driversTitle: 'Что движет ростом',
  },
  human: {
    eyebrow: 'Человеческий капитал',
    title: 'Молодая страна',
    body: 'Демография и рынок труда — рабочая сила за каждым проектом.',
    salaryTitle: 'Средняя месячная зарплата по регионам',
    salaryUnit: 'тыс. сум / месяц',
    nationalAverage: 'Среднее по стране',
    populationNote:
      'Две официальные страницы дают две разные цифры населения за 2025 год. Обе показаны со своей пометкой, без усреднения.',
  },
  sectors: {
    eyebrow: 'Приоритетные отрасли',
    title: 'Десять отраслей, открытых для инвестиций',
    body: 'Найдите нужную отрасль и откройте её страницу на сайте Агентства.',
    searchLabel: 'Поиск по отраслям',
    searchPlaceholder: 'Поиск по названию…',
    count: (n: number, total: number) => `${n} из ${total} отраслей`,
    modalNote:
      'Агентство не публикует краткое описание для каждой отрасли. Откройте официальную страницу, чтобы увидеть актуальные условия и проекты.',
  },
  services: {
    eyebrow: 'Чем занимается Агентство',
    title: 'Единое окно',
    body: 'Пять услуг для иностранных инвесторов и полномочия, на которых они основаны.',
    functionsTitle: 'Основные функции',
    legalBasis: 'Правовое основание',
  },
  sez: {
    eyebrow: 'Специальные экономические зоны',
    title: 'Зоны и льготы',
    body: 'Что такое зоны, что они дают и где проходят границы этого предложения.',
    zoneTypesTitle: 'Типы зон',
    disclaimerTitle: 'Это не налоговая и не юридическая консультация',
  },
  strategy: {
    eyebrow: 'Узбекистан — 2030',
    title: 'Пять приоритетов, сто целей',
    goalsLabel: 'целей',
    adopted: 'Принята',
    targetsTitle: 'Заявленные цели',
    progressTitle: 'С момента принятия',
  },
  tiif: {
    eyebrow: 'Ташкентский международный инвестиционный форум',
    title: 'ТМИФ 2026 — итоги пятого форума',
    pastNotice: 'Форум уже состоялся. Ниже — его опубликованные результаты.',
    heldOn: 'Проведён',
    attendeesTitle: 'Представленные организации',
    attendeesNote: 'Названия приведены только текстом; логотипы третьих сторон не используются.',
    officialSite: 'Сайт форума',
  },
  journey: {
    eyebrow: 'Как это работает',
    title: 'От первого обращения до сопровождения',
    stepLabel: (n: number) => `Шаг ${n}`,
  },
  faq: {
    eyebrow: 'Вопросы',
    title: 'Часто задаваемые',
    searchLabel: 'Поиск по вопросам',
    searchPlaceholder: 'Поиск по ответам…',
  },
  contact: {
    eyebrow: 'Связаться',
    title: 'Отправить инвестиционный запрос',
    body: 'Агентство — основная точка контакта с государством для иностранных инвесторов.',
    phone: 'Телефон',
    email: 'Электронная почта',
    address: 'Адрес',
    openMap: 'Открыть на карте',
    draftSaved: 'Черновик сохранён',
    draftRestored: 'Ваш неотправленный черновик восстановлен.',
    clearDraft: 'Очистить форму',
    form: {
      name: 'Полное имя',
      company: 'Компания',
      country: 'Страна',
      email: 'Рабочая почта',
      sector: 'Интересующая отрасль',
      sectorAny: 'Пока не определено',
      amount: 'Планируемые инвестиции',
      amountAny: 'Предпочитаю не указывать',
      message: 'Что вы хотели бы обсудить?',
      submit: 'Отправить запрос',
      submitting: 'Отправка…',
      required: 'Обязательно',
      optional: 'Необязательно',
    },
    errors: {
      nameRequired: 'Укажите ваше имя.',
      nameShort: 'Введите хотя бы два символа.',
      emailRequired: 'Укажите адрес электронной почты.',
      emailInvalid: 'Это не похоже на адрес электронной почты.',
      messageRequired: 'Напишите, что вы хотели бы обсудить.',
      messageShort: 'Достаточно одного-двух предложений.',
      countryRequired: 'Укажите вашу страну.',
    },
    success: {
      title: 'Спасибо — ваш запрос готов к отправке',
      mailto:
        'Почтовый клиент должен был открыться с готовым письмом. Если этого не произошло, напишите на адрес выше.',
      posted: 'Ваш запрос отправлен.',
    },
    failure: {
      title: 'Не удалось отправить запрос',
      body: 'Пожалуйста, напишите на адрес выше.',
    },
  },
  fx: {
    label: 'Курс Центрального банка',
    live: 'Актуальный',
    stored: 'Сохранённый курс',
    asOf: (date: string) => `на ${date}`,
    unavailable: 'Курс недоступен',
  },
  sources: {
    label: 'Источник',
    asOf: (date: string) => `Данные на ${date}`,
    sectionTitle: 'Источники',
    sectionBody: 'Каждая цифра на странице взята из одного из источников ниже, на указанную дату.',
    verifyBadge: 'Проверить перед публикацией',
    machineTranslation:
      'Русский текст на этой странице переведён с английского и не является официальным.',
  },
  footer: {
    usefulLinks: 'Официальные ссылки',
    disclaimerTitle: 'Концептуальный проект',
    disclaimer:
      'Этот сайт — концепт/демо и не ведётся Агентством. За официальной информацией обращайтесь на invest.gov.uz.',
    rights: (year: number) => `© ${year} — концептуальный проект`,
  },
};

export const UI = { uz, ru, en } as const;
